version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch-node-browsers
        environment:
          - TEST_DATABASE_URL=postgresql://root@localhost/example_project
          - CI=True
      - image: circleci/postgres:9.6.11
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=example_project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install libgeoip-dev
            if psql demo -c ''; then dropdb demo; fi
            sudo pip install --upgrade pip setuptools cookiecutter python-coveralls
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            . ~/.nvm/nvm.sh
            npm install --global yarn

      - run:
          name: Install PostgreSQL client
          command: |
            echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
            wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install libpq5 postgresql-client-9.6
            sudo createuser -h localhost -s circleci

      - run:
          name: Run cookiecutter
          command: |
            cookiecutter --no-input -f -o . --config-file tests/cookiecutter.yml .

      - run:
          name: Install project dependencies
          command: |
            cd demo/ && . .venv/bin/activate
            pip install --upgrade pip
            pip install pytest==5.2.1 pytest-cov==2.8.1 pytest-django==3.5.1

      - run:
          name: Test project
          command: |
            cd demo && . .venv/bin/activate
            . ~/.nvm/nvm.sh
            nvm use
            yarn run lint:css
            yarn run lint:js
            yarn run lint:python
            yarn run lint:isort
            pytest --cov=demo --create-db --nomigrations --ds=demo.settings.local

workflows:
  version: 2
  test:
    jobs:
      - build
