version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-jessie-node-browsers
        environment:
            TEST_DATABASE_URL: postgresql://root@localhost/example_project
      - image: circleci/postgres:9.5.10
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=example_project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install libgeoip-dev
            if psql demo -c ''; then dropdb demo; fi
            sudo pip install --upgrade pip setuptools cookiecutter python-coveralls
            sudo npm install --global yarn
            sudo apt-get install postgresql-client-9.6

      - run:
          name: Run cookiecutter
          command: |
            sudo cookiecutter --no-input -f -o . --config-file tests/cookiecutter.yml .

      - run:
          name: Install project dependencies
          command: |
            deactivate && cd demo/ && . .venv/bin/activate && pip install cryptography pygithub
            deactivate && cd demo/ && . .venv/bin/activate && pip install --upgrade pytest pytest-cov pytest-django pylint==1.7.5 pylint-django==0.7.2 pylint-mccabe==0.1.3 isort==4.2.15 astroid==1.5.3

      - run:
          name: Test project
          command: |
            deactivate && cd demo/ && . .venv/bin/activate && pylint demo/ --load-plugins pylint_django,pylint_mccabe --ignore=migrations,tests -d missing-docstring,invalid-name,no-init,too-many-ancestors,no-member,line-too-long,attribute-defined-outside-init,too-few-public-methods,no-self-use,unused-argument,protected-access,locally-disabled,duplicate-code --reports=n
            deactivate && cd demo/ && . .venv/bin/activate && isort --check-only --diff --quiet --skip-glob=.venv --skip-glob=node_modules --skip-glob=*/migrations/*
            deactivate && cd demo/ && . .venv/bin/activate && yarn run lint:css
            deactivate && cd demo/ && . .venv/bin/activate && yarn run lint:js
            deactivate && cd demo/ && . .venv/bin/activate && pytest --cov=demo --create-db --nomigrations --ds=demo.settings.local

workflows:
  version: 2
  test:
    jobs:
      - build
