# Generated by Django 2.2.9 on 2020-10-29 11:06

import cms.apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailData',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('rendered', models.BooleanField(default=False)),
                ('options_json', models.TextField(blank=True)),
                ('media_file', models.FileField(max_length=250, storage=cms.apps.media.models.MediaStorage(), upload_to='uploads/files')),
            ],
            options={
                'select_on_save': True,
            },
        ),
    ]
