# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_auto_20151002_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('terms_of_use_link', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_link', models.CharField(blank=True, max_length=255, null=True)),
                ('privacy_policy_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='If you want to link to an external page, please use this.', max_length=200, null=True)),
                ('order', models.PositiveIntegerField()),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.Footer')),
                ('link_page', models.ForeignKey(blank=True, help_text='If you want to link to an internal page, please use this.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.Page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_search', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, help_text='If you want to link to an external page, please use this.', max_length=200, null=True)),
                ('order', models.PositiveIntegerField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.Header')),
                ('link_page', models.ForeignKey(blank=True, help_text='If you want to link to an internal page, please use this.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.Page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
